# Default colors
[colors.primary]
background = "#151515"
foreground = "#c0caf5"

# Cursor colors
[colors.cursor]
cursor = "#c0caf5"
text = "#151515"

# Normal colors
[colors.normal]
black = "#151515"
red = "#f76668"
green = "#9ece6a"
yellow = "#e08d5c"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#d6d6d6"

# Bright colors
[colors.bright]
black = "#414868"
red = "#f76062"
green = "#9ece6a"
yellow = "#e0a35d"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#f5f5f5"
