# Default colors
[colors.primary]
background = "#161616"
foreground = "#ffffff"

# Cursor colors
[colors.cursor]
cursor = "#33b1ff"
text = "#161616"

# Normal colors
[colors.normal]
black = "#262626"
red = "#ff4e4e"
green = "#42be65"
yellow = "#ff815a"
blue =  "#33b1ff"
magenta = "#ff4073"
cyan = "#3ddbd9"
white = "#dde1e6"

# Bright colors
[colors.bright]
black = "#393939"
red = "#ff4e4e"
green = "#42be65"
yellow = "#ff815a"
blue =  "#33b1ff"
magenta = "#ff4073"
cyan = "#3ddbd9"
white = "#ffffff"
